/* #undef HAS_ATTRIBUTE_UNUSED */
/* #undef HAS_ATTRIBUTE_DEPRECATED */
/* #undef HAS_ATTRIBUTE_DEPRECATED_MSG */
/* #undef HAVE_ARRAY */
/* #undef HAVE_BOOST_MAKE_SHARED_HPP */
/* #undef HAVE_BOOST_SHARED_PTR_HPP */
#define HAVE_DUNE_BOOST 1
/* #undef HAVE_GMP */
/* #undef HAVE_MAKE_SHARED */
/* #undef HAVE_MPI */
/* #undef HAVE_NULLPTR */
/* #undef HAVE_STATIC_ASSERT */
/* #undef HAVE_SHARED_PTR */
/* #undef MPI_2 */
/* #undef SHARED_PTR_HEADER */
/* #undef SHARED_PTR_NAMESPACE */
/* #undef HAVE_TYPE_TRAITS */
/* #undef HAVE_TR1_TUPLE */
/* #undef HAVE_TUPLE */
/* #undef HAVE_CXA_DEMANGLE */
/* #undef HAVE_ALGLIB */
/* #undef HAVE_UG */
/* #undef HAVE_DUNE_FEM */
/* #undef HAVE_GRIDTYPE */
/* #undef HAVE_GRAPE */
/* #undef HAVE_PSURFACE */
/* #undef HAVE_AMIRAMESH */
/* #undef HAVE_ALBERTA */
/* #undef HAVE_STDINT_H */
#define DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS 1
/* #undef DUNE_ALBERTA_VERSION */
#define HAVE_OPENMP 1
#define DUNE_GRID_VERSION_MAJOR 2
#define DUNE_GRID_VERSION_MINOR 9
#define DUNE_GRID_VERSION_REVISION 0
#define DUNE_GEOMETRY_VERSION_MAJOR 2
#define DUNE_GEOMETRY_VERSION_MINOR 9
#define DUNE_GEOMETRY_VERSION_REVISION 0
#define DUNE_COMMON_VERSION_MAJOR 2
#define DUNE_COMMON_VERSION_MINOR 9
#define DUNE_COMMON_VERSION_REVISION 0
/* #undef HAVE_DUNE_ISTL */
/* #undef HAVE_ZOLTAN */
#define HAVE_OPM_COMMON 1
#define HAVE_ECL_INPUT 1
#define HAVE_DUNE_GRID_CHECKS 0
#define HAVE_DYNAMIC_BOOST_TEST 0
