# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  jobs:
    post_install:
      - echo `ls`
      - cd `darts-package/`
      - echo `ls`
      - python3 setup.py build bdist_wheel
      - pip install --upgrade --no-deps --force-reinstall dist/*.whl
      - pip install -r darts/docs/requirements.txt
      - cd `../`
      - echo `ls`

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: darts-package/darts/docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats: [pdf]

# Optionally set the version of Python and requirements required to build your docs
#python:
#  install:
#    - requirements: darts-package/darts/docs/requirements.txt
#    - method: setuptools
#      path: ./darts-package/

