ARG VERSION
FROM nvidia/cuda:${VERSION}-base

ADD dist/*.whl . 

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools \
    libcublas-11-2 \
    libcusparse-11-2 \
    libcusolver-11-2 \
    && python3 -m pip install wheel \
    #&& python3 -m pip install --find-links=dist/ darts \
    && python3 -m pip install darts-0.1.0-cp38-cp38-linux_x86_64.whl \
    && apt-mark hold libnccl-dev \
    && rm -rf /var/lib/apt/lists/*


