ARG VERSION
FROM nvidia/cuda:${VERSION}-devel

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-setuptools \
    python3-dev \
    git \
    cmake \
    && apt-mark hold libnccl-dev \
    && rm -rf /var/lib/apt/lists/*
